FROM python:3
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /mysite
COPY requirements.txt /mysite/
RUN pip3 install -r requirements.txt
COPY . /mysite/
EXPOSE 8000
EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]