#ifndef OOP_1_ERRORS_PROCESSING_H
#define OOP_1_ERRORS_PROCESSING_H

enum errors
{
    SUCCESS = 0,
    INV_FILE,
    INV_SIZE,
    INV_SIZE_READ,
    INV_MALLOC_COORD,
    INV_INIT_MODEL,
    INV_SCENE,
    INV_VERTEX,
    INV_MALLOC_ADJ_MATR
};

#endif //OOP_1_ERRORS_PROCESSING_H
