FROM python:3
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /log
COPY requirements.txt /log/
RUN pip3 install -r requirements.txt
COPY . /log/
EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]