# Generated by Django 3.2.8 on 2022-06-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('surname', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('inn', models.IntegerField(null=True)),
                ('series_passport', models.IntegerField(null=True)),
                ('number_passport', models.IntegerField(null=True)),
                ('position', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
