# Generated by Django 3.2.8 on 2022-06-07 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Empl',
        ),
    ]
